import React, { Component } from "react"

const IconCalendar = props => {
  return (
    <div className="icon-container">
      <svg
        width="227px"
        height="224px"
        viewBox="0 0 227 224"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        className="icon-calendar"
      >
        <title>lsml-cal-gs</title>
        <g
          id="lsml-cal-gs"
          stroke="none"
          strokeWidth="1"
          fill="none"
          fillRule="evenodd"
          className="icon-gs"
        >
          <rect
            id="Rectangle"
            fill="#E2E8F0"
            x="0"
            y="23"
            width="227"
            height="201"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy"
            fill="#4A5568"
            x="8"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-9"
            fill="#E2E8F0"
            x="38"
            y="0"
            width="15"
            height="35"
            rx="4"
          ></rect>
          <rect
            id="Rectangle-Copy-10"
            fill="#E2E8F0"
            x="173"
            y="0"
            width="15"
            height="35"
            rx="4"
          ></rect>
          <rect
            id="Rectangle-Copy-2"
            fill="#4A5568"
            x="52"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-3"
            fill="#4A5568"
            x="96"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-7"
            fill="#4A5568"
            x="182"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-6"
            fill="#4A5568"
            x="139"
            y="63"
            width="36"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-4"
            fill="#4A5568"
            x="8"
            y="140"
            width="102"
            height="57"
            rx="3"
          ></rect>
          <rect
            id="Rectangle-Copy-5"
            fill="#4A5568"
            x="117"
            y="140"
            width="102"
            height="57"
            rx="3"
          ></rect>
        </g>
        <g
          id="lsml-cal-col"
          stroke="none"
          stroke-width="1"
          fill="none"
          fill-rule="evenodd"
          className="icon-color"
        >
          <rect
            id="Rectangle"
            stroke="#007ACE"
            stroke-width="3"
            fill="#007ACE"
            x="2"
            y="23"
            width="227"
            height="201"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy"
            fill="#ECC94C"
            x="10"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-9"
            fill="#D63A26"
            x="40"
            y="0"
            width="15"
            height="35"
            rx="4"
          ></rect>
          <rect
            id="Rectangle-Copy-10"
            fill="#D63A26"
            x="175"
            y="0"
            width="15"
            height="35"
            rx="4"
          ></rect>
          <rect
            id="Rectangle-Copy-2"
            fill="#ECC94C"
            x="54"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-3"
            fill="#ECC94C"
            x="98"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-7"
            fill="#ECC94C"
            x="184"
            y="63"
            width="37"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-6"
            fill="#ECC94C"
            x="141"
            y="63"
            width="36"
            height="70"
            rx="2"
          ></rect>
          <rect
            id="Rectangle-Copy-4"
            fill="#ECC94C"
            x="10"
            y="140"
            width="102"
            height="57"
            rx="3"
          ></rect>
          <rect
            id="Rectangle-Copy-5"
            fill="#ECC94C"
            x="119"
            y="140"
            width="102"
            height="57"
            rx="3"
          ></rect>
        </g>
      </svg>
    </div>
  )
}

export default IconCalendar
