import React, { Component } from "react"

const IconGrid = props => {
  return (
    <div className="icon-container">
      <svg
        width="233px"
        height="233px"
        viewBox="0 0 233 233"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        className="icon-grid"
      >
        <title>lsml-grid</title>
        <g
          id="lsml-grid-gs"
          stroke="none"
          stroke-width="1"
          fill="none"
          fill-rule="evenodd"
          className="icon-gs"
        >
          <rect
            id="Rectangle"
            fill="#E2E8F0"
            x="0"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy"
            fill="#E2E8F0"
            x="0"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-7"
            fill="#E2E8F0"
            x="60"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-6"
            fill="#E2E8F0"
            x="60"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-2"
            fill="#E2E8F0"
            x="0"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-3"
            fill="#E2E8F0"
            x="0"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-4"
            fill="#E2E8F0"
            x="60"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-5"
            fill="#E2E8F0"
            x="60"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-15"
            fill="#E2E8F0"
            x="120"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-14"
            fill="#E2E8F0"
            x="120"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-13"
            fill="#E2E8F0"
            x="180"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-12"
            fill="#E2E8F0"
            x="180"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-11"
            fill="#E2E8F0"
            x="120"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-10"
            fill="#E2E8F0"
            x="120"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-9"
            fill="#E2E8F0"
            x="180"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-8"
            fill="#E2E8F0"
            x="180"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
        </g>
        <g
          id="lsml-grid-col"
          stroke="none"
          stroke-width="1"
          fill="none"
          fill-rule="evenodd"
          className="icon-color"
        >
          <rect
            id="Rectangle"
            fill="#D63A26"
            x="0"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy"
            fill="#D63A26"
            x="0"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-7"
            fill="#ECC94C"
            x="60"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-6"
            fill="#ECC94C"
            x="60"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-2"
            fill="#D63A26"
            x="0"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-3"
            fill="#D63A26"
            x="0"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-4"
            fill="#ECC94C"
            x="60"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-5"
            fill="#ECC94C"
            x="60"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-15"
            fill="#2DA56A"
            x="120"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-14"
            fill="#2DA56A"
            x="120"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-13"
            fill="#007ACE"
            x="180"
            y="0"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-12"
            fill="#007ACE"
            x="180"
            y="60"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-11"
            fill="#2DA56A"
            x="120"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-10"
            fill="#2DA56A"
            x="120"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-9"
            fill="#007ACE"
            x="180"
            y="180"
            width="53"
            height="53"
            rx="8"
          ></rect>
          <rect
            id="Rectangle-Copy-8"
            fill="#007ACE"
            x="180"
            y="120"
            width="53"
            height="53"
            rx="8"
          ></rect>
        </g>
      </svg>
    </div>
  )
}

export default IconGrid
